# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 07:09
from __future__ import unicode_literals

# from datetime import datetime
#
# from django.contrib.auth.hashers import make_password
from django.db import migrations

#
# def load_user(apps, schema_editor):
#     User = apps.get_model('users', 'User')
#     user_data = User(pk=1, username='ctalluitel', first_name='Shital', last_name='Luitel', password=make_password('shital1'),
#                      is_confirmed=True, created_at=datetime.today())
#     user_data.save()


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        # migrations.RunPython(load_user)
    ]
