# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171012_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'User with this username already exists.'}, max_length=255, unique=True, validators=[users.validators.UsernameValidator()]),
        ),
    ]
