# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 07:22
from __future__ import unicode_literals

from datetime import datetime
from django.contrib.auth.hashers import make_password
from django.db import migrations


def load_user(apps, schema_editor):
    User = apps.get_model('users', 'User')
    user_data = User(pk=1, username='ctalluitel', email='ctalluitel@gmail.com', first_name='Shital', last_name='Luitel',
                     password=make_password('shital.87'),
                     is_confirmed=True, created_at=datetime.today())
    user_data.save()


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_auto_20171012_0718'),
    ]

    operations = [
        migrations.RunPython(load_user)
    ]
